### ISSUE TITLE
Storage efficiency

### ISSUE THREAD

**Issue by joernu76** [Marilyth/mss-data-retrieval#1]
I tried the script and everything seems to work :-)

I noticed though, that the resulting data is a bit all over the place with used NetCDF variety.
```
$ for i in *nc; do echo $i `ncdump -k $i`; done
2020-01-01T12:00:00.an.al.nc 64-bit offset
2020-01-01T12:00:00.an.ml.nc netCDF-4 classic model
2020-01-01T12:00:00.an.pl.nc 64-bit offset
2020-01-01T12:00:00.an.pv.nc netCDF-4
2020-01-01T12:00:00.an.sfc.nc netCDF-4 classic model
2020-01-01T12:00:00.an.tl.nc netCDF-4
```
I would suggest to use netCDF-4 classic model unless there is a good reason to do something else.

Second with resulting file size. We should use the netCDF4 in-built compression with a default compression level.
But this is interesting:

```
$ ncks -7 2020-01-01T12:00:00.an.tl.nc a.nc
$ ncks -7 -L7 2020-01-01T12:00:00.an.tl.nc b.nc
$ grib_to_netcdf ../grib/2020-01-01T12:00:00.an.tl.grib -o c.nc
$ ncks -7 -L7 c.nc d.nc
$ ls -l ../grib/*tl.grib *tl.nc ?.nc
6.3M Apr 15 16:22 2020-01-01T12:00:00.an.tl.grib
19M Apr 15 16:22 2020-01-01T12:00:00.an.tl.nc
19M Apr 19 15:01 a.nc
9.5M Apr 19 15:05 b.nc
6.6M Apr 19 15:01 c.nc
3.7M Apr 19 15:08 d.nc
```

With proper parameters we get a file size reduction of factor 2, but grib_to_netcdf achieves a factor of 3. It achieves this by using "short" as data type (instead of float) with scale and offset. We can then compress this on top to get a factor of ~6, which is actually *smaller* than the grib file...

**Comment by Marilyth** [comment]
Should be resolved now.

I found `grib_to_netcdf` to be a bit problematic in how it sometimes tends to drastically change the files contents and isn't compatible with sfc+ml files.
I could eventually try and rewrite everything to work with eccodes approach.

For now I simply applied the L7 compression together with conversion to short via NCOs `ncpdq` and get roughly the same compression as you got with d.nc (3.9 vs 3.7).

**Comment by joernu76** [comment]
The idea is less to use the tool itself, but maybe to write a converter (for our use) to use the strange storage technique.

The sizes suggest that grib itself stores the data in this fashion (maybe compressed per layer??).
In this case we would not loose much to use the short+scale/offset technique for most quantities except, maybe, pressure?

Especially for storing large amount of data, this could be very practical (less for MSS). I have 8 TiB of ECMWF model data on a 24TiB RAID, which could be reduced to 2-3 TiB.
Maybe the CLaMS group could also make use of this to conserve space.

**Comment by Marilyth** [comment]
I am not sure I understand. Why can't you use the "strange storage technique" already implemented, optimised and maintained by NCO?

**Comment by joernu76** [comment]
We could. But we can choose to store the data in float (and use netCDF/HDF5 compression) as done by cdo, or store the data in short (and use netCDF/HDF5  compression), which is not done by cdo.
I do not know, if one can convert a file from float to short+scale/offset with a tool from the NCO tool suite. This is a dangerous game to play as this is a fixed point precision, which can deterioate the quality of data if it spans several orders of magnitude. float is much safer there. But that grib_to_ncdf uses this technique, points to the fact that, hopefully, someone smarter than me has thought about this and decided that this technique can be used here without causing problems.
Again, for pressure I would double check that, but the other quantities should be storable using this fixed point precision technique.
And the netCDF4 python module nicely takes care of the conversion to float when reading the data!
You can see the difference in the files only using, e.g., "ncdump -h", which gives you the data types.

**Comment by joernu76** [comment]
I had a short look into that. The NCO tool ncpdq can do the float->short compression. In principle. In practice I had quite a bit of issues with this. Fixing this manually, I got the following results:
151M Apr 20 10:40 tst_float_ncdf3.nc
  95M Apr 20 10:41 tst_float_ncdf4.nc
  76M Apr 20 10:55 tst_shrt_ncdf3.nc
  41M Apr 20 11:01 tst_shrt_ncdf4.nc

So a factor of 2 could be gained over the current float/ncdf4 storage. The short packing is fully unproblematic for winds, temperatures and may other quantities. PV has some issues with the discretization and some few other quantities.
The ncpdq tool has issues with missing_values and fill-values of NaN.

So, currently I would define this as out-of-scope for this activity. To fiddly. I'll pick it up for storage of my data. Still only doing this for safe quantities could free up some TiB on my most used RAID.
